# Задание на повторение материала

### Задание 1
Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [1]:
import numpy as np
from numpy import linalg
import random

In [2]:
a = np.arange(12, 24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

### Задание 2
Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [3]:
a1 = a.reshape(2, 6)
a2 = a.reshape(3, 4)
a3 = a.reshape(6, 2)
a4 = a.reshape(4, 3)
a5 = a.reshape(12, 1)
print("a1:", a1)
print("a2:", a2)
print("a3:", a3)
print("a4:", a4)
print("a5:", a5)

a1: [[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
a2: [[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
a3: [[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
a4: [[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
a5: [[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


### Задание 3
Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [4]:
a6 = a.reshape(4, -1)
a7 = a.reshape(6, -1)
a8 = a.reshape(3, -1)
a9 = a.reshape(-1, 12)
a10 = a.reshape(-1, 1)
print("a6:", a6)
print("a7:", a7)
print("a8:", a8)
print("a9:", a9)
print("a10:", a10)

a6: [[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
a7: [[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
a8: [[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
a9: [[12 13 14 15 16 17 18 19 20 21 22 23]]
a10: [[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


### Задание 4 
Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

In [5]:
a5.ndim

2

Массив Numpy, состоящий из одного столбца и 12 строк, - двумерный

### Задание  5
Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.


In [6]:
a = np.random.randn(3,4)
a

array([[ 1.2182136 ,  0.64797165,  0.06155876, -0.99051916],
       [ 0.28470922, -0.01168139,  0.13535328,  0.45431902],
       [ 1.70742785,  1.04928028,  0.44117172,  0.58248542]])

In [7]:
b = a.flatten()
b

array([ 1.2182136 ,  0.64797165,  0.06155876, -0.99051916,  0.28470922,
       -0.01168139,  0.13535328,  0.45431902,  1.70742785,  1.04928028,
        0.44117172,  0.58248542])

In [8]:
a.size == b.size

True

### Задание 6
Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [9]:
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

### Задание 7
Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

In [10]:
b = np.arange(20, 1, -2).reshape(1,10)
b

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

a - одномерный массив,
b - двумерный массив

### Задание 8
Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. 

In [11]:
a = np.zeros((2, 2))
a

array([[0., 0.],
       [0., 0.]])

In [12]:
b = np.ones((3, 2))
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

Итоговый массив v должен иметь атрибут size, равный 10.

In [13]:
v = np.vstack((a, b))
v

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [14]:
v.size

10

### Задание 9
Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов.

In [15]:
a = np.arange(0, 12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [16]:
A = a.reshape(4, 3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

Получить матрицу At путем транспонирования матрицы A. 

In [17]:
At = A.T
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. 

In [18]:
B = A.dot(At)
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

Какой размер имеет матрица B? 

In [19]:
B.shape

(4, 4)

Получится ли вычислить обратную матрицу для матрицы B и почему?

In [20]:
B_inv = linalg.inv(B)
B_inv

LinAlgError: Singular matrix

Обратную матрицу для матрицы B вычислить не получится, так как матрица B является сингулярной, то есть определитель = 0

### Задание 10
Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [21]:
np.random.seed(42)

### Задание 11
Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 

In [22]:
c = np.random.randint(0, 16,16)
c

array([ 6,  3, 12, 14, 10,  7, 12,  4,  6,  9,  2,  6, 10, 10,  7,  4])

### Задание 12
Поменяйте его форму так, чтобы получилась квадратная матрица C. 

In [23]:
C = c.reshape(4,4)
C

array([[ 6,  3, 12, 14],
       [10,  7, 12,  4],
       [ 6,  9,  2,  6],
       [10, 10,  7,  4]])

Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. 

In [24]:
D = B + C * 10
D

array([[ 65,  44, 143, 172],
       [114, 120, 206, 162],
       [ 83, 176, 169, 272],
       [132, 222, 282, 342]])

Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [25]:
np.linalg.det(D)

-28511999.999999944

In [26]:
linalg.matrix_rank(D) 

4

In [27]:
D_inv = linalg.inv(D)
D_inv

array([[ 0.00935396,  0.04486532,  0.05897517, -0.07286055],
       [-0.01503577, -0.00122896, -0.00192971,  0.00967873],
       [-0.00356692, -0.01782828, -0.04152146,  0.04326178],
       [ 0.00909091, -0.00181818,  0.01272727, -0.01090909]])

### Задание 13
Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. 

In [28]:
D_inv=np.where(D_inv < 0, 0, 1)
D_inv

array([[1, 1, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [1, 0, 1, 0]])

С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [29]:
print(B)
print(C)
E = np.where(D_inv == 1, B, C)
E

[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]
[[ 6  3 12 14]
 [10  7 12  4]
 [ 6  9  2  6]
 [10 10  7  4]]


array([[  5,  14,  23,  14],
       [ 10,   7,  12, 122],
       [  6,   9,   2, 212],
       [ 32,  10, 212,   4]])